// Uses tests/ems_erp_preview.py and isolated Chrome CDP on port 9233.
const assert=require('node:assert/strict');
(async()=>{
 const origin='http://127.0.0.1:8012',base=origin+'/erp';
 async function login(email){const r=await fetch(base+'/auth/login',{method:'POST',body:new URLSearchParams({username:email,password:'PreviewOnly123'})});assert.equal(r.status,200);return (await r.json()).access_token;}
 const adminToken=await login('admin@ems.test'),employeeToken=await login('employee@ems.test');
 const request=async(path,token,method='GET',body)=>fetch(base+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const employee=await(await request('/api/ems/me',employeeToken)).json();
 const target=(await(await fetch('http://127.0.0.1:9233/json')).json()).find(t=>t.type==='page');
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expression=>{for(let n=0;n<100;n++){try{if(await evaluate(expression))return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+expression);};
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const form=(values)=>evaluate(`(()=>{const f=document.getElementById('dialogForm');for(const [key,value] of Object.entries(${JSON.stringify(values)}))f.elements[key].value=value;f.requestSubmit(f.querySelector('button.primary'));})()`);
 const navigate=async()=>{await call('Page.navigate',{url:base+'/ems'});await wait('document.querySelector(".welcome")!==null');};
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:base+'/login'});await wait('location.pathname==="/erp/login"&&document.readyState==="complete"');
 await evaluate(`localStorage.setItem('token',${JSON.stringify(adminToken)});localStorage.setItem('role','Admin')`);
 await navigate();
 assert.equal(await evaluate('document.documentElement.dataset.erp'),'true');
 assert.equal(await evaluate('document.querySelector("[data-view=employees]")!==null'),true);
 assert.equal(await evaluate('document.querySelector(".brand").getAttribute("href")'),'/erp/home');
 await click('[data-view="rewards"]');await wait('document.querySelector("[data-action=new-earning]")!==null');await click('[data-action="new-earning"]');
 await form({user_id:String(employee.id),month:'2026-09',kind:'bonus',amount:'1000.25',note:'ERP award'});
 await wait('document.getElementById("message").textContent.includes("Earning approved")');
 await click('[data-view="payroll"]');await wait('document.querySelector("[data-action=new-payroll]")!==null');await click('[data-action="new-payroll"]');
 await form({user_id:String(employee.id),month:'2026-09',basic:'20000',allowances:'0',deductions:'100'});
 await wait('document.getElementById("message").textContent.includes("Payslip published")');
 await evaluate('window.print=()=>{window.didPrint=true}');await click('[data-action="payslip"]');await wait('window.didPrint===true');
 assert.equal(await evaluate(`document.getElementById('printArea').textContent.includes(${JSON.stringify(employee.employee_id)})`),true);
 await evaluate('window.dispatchEvent(new Event("afterprint"))');
 await evaluate(`localStorage.setItem('token',${JSON.stringify(employeeToken)});localStorage.setItem('role','Employee')`);await navigate();
 assert.equal(await evaluate('document.querySelector("[data-view=employees]")===null'),true);
 await click('[data-view="payroll"]');await wait('document.querySelector("tbody")!==null');
 assert.equal(await evaluate('document.querySelectorAll("tbody tr").length'),1);
 assert.equal(await evaluate('document.getElementById("content").textContent.includes("20,900.25")'),true);
 await click('[data-view="profile"]');await wait('document.getElementById("profileForm")!==null');
 assert.equal(await evaluate('document.querySelector("#profileForm [name=name]").disabled'),true);
 await click('[data-view="leave"]');await wait('document.querySelector("[data-action=new-leave]")!==null');await click('[data-action="new-leave"]');
 const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 await form({start_date:day,end_date:day,kind:'Casual',reason:'ERP leave test'});await wait('document.getElementById("message").textContent.includes("sent to HR")');
 const leave=(await(await request('/api/ems/leave',employeeToken)).json())[0];
 assert.equal((await request('/api/ems/leave/'+leave.id,adminToken,'PUT',{status:'approved'})).status,200);
 assert.equal((await request('/api/me/attendance-status',employeeToken,'PUT',{on_leave:false})).status,409);
 await click('[data-view="attendance"]');await wait('document.querySelector("[data-action=check-in]")!==null');await click('[data-action="check-in"]');await wait('location.pathname==="/erp/attendance"');
 await navigate();await click('[data-view="identity"]');await wait('location.pathname==="/erp/identity-card"');
 await navigate();await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 assert.equal((await request('/api/ems/employees',employeeToken)).status,403);
 console.log('PASS: full ERP /erp route, shared Bearer login, payroll/rewards, correct employee ID on payslip, employee scoping, protected leave, attendance and identity links, mobile layout.');
 ws.close();
})().catch(error=>{console.error(error);process.exit(1)});
