const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const target=(await(await fetch('http://127.0.0.1:9231/json')).json()).find(t=>t.url.includes('/identity-card'));
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expression=>{for(let n=0;n<60;n++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+expression);};
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1150,deviceScaleFactor:1,mobile:false});
 await call('Page.reload',{ignoreCache:true});
 await wait('document.querySelectorAll(".person").length===2');
 assert.equal(await evaluate('document.querySelectorAll("#preview .id-card").length'),2);
 assert.equal(await evaluate('document.querySelector("[name=employee_id]").readOnly'),true);
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 await wait('[...document.querySelectorAll("#preview img")].every(img=>img.complete&&img.naturalWidth>0)');
 let screenshot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('tmp/identity-desktop.png',Buffer.from(screenshot.data,'base64'));
 await evaluate(`document.getElementById('search').value='Meera';document.getElementById('search').dispatchEvent(new Event('input'));`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),1);
 await evaluate(`document.querySelector('.person').click();const name=document.querySelector('[name=employee_name]');name.value='Meera & <Kapoor>';name.dispatchEvent(new Event('input',{bubbles:true}));`);
 assert.equal(await evaluate('document.querySelector(".card-data .name").textContent'),'Meera & <Kapoor>');
 assert.equal(await evaluate('document.querySelector(".card-data .name").children.length'),0);
 await evaluate(`document.getElementById('editor').requestSubmit()`);
 await wait(`document.getElementById('message').textContent.includes('saved successfully')`);
 await call('Page.reload',{ignoreCache:true});await wait('document.querySelectorAll(".person").length===2');
 await evaluate(`document.querySelector('[data-user="2"]').click()`);
 assert.equal(await evaluate('document.querySelector(".card-data .name").textContent'),'Meera & <Kapoor>');
 await evaluate(`window.print=()=>{window.printRequested=true};document.getElementById('printAll').click()`);
 await wait('window.printRequested===true');
 assert.equal(await evaluate('document.querySelectorAll("#printArea .id-card").length'),4);
 await call('Emulation.setEmulatedMedia',{media:'print'});
 assert.equal(await evaluate('Math.round(document.querySelector("#printArea .id-card").getBoundingClientRect().width)'),204);
 await call('Emulation.setEmulatedMedia',{media:''});
 await evaluate(`window.dispatchEvent(new Event('afterprint'))`);
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 await evaluate('scrollTo(0,400)');
 screenshot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('tmp/identity-mobile.png',Buffer.from(screenshot.data,'base64'));
 // Long allowed values must remain above the card footer.
 await evaluate(`const fields={employee_name:'A very long employee name '.repeat(6).slice(0,150),designation:'Senior regional operations and customer experience manager '.repeat(2).slice(0,100)};for(const [key,value] of Object.entries(fields)){const input=document.querySelector('[name='+key+']');input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));}`);
 assert.equal(await evaluate('document.querySelector(".card-data").getBoundingClientRect().bottom<document.querySelector(".id-front footer").getBoundingClientRect().top'),true);
 await evaluate(`document.querySelector('[name=employee_name]').value='Meera Kapoor';document.querySelector('[name=employee_name]').dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('editor').requestSubmit()`);
 await wait(`document.getElementById('message').textContent.includes('saved successfully')`);
 await evaluate(`window.printRequested=false;document.getElementById('printAll').click()`);
 await wait('window.printRequested===true');
 await call('Emulation.setEmulatedMedia',{media:'print'});
 await evaluate(`window.dispatchEvent(new Event('beforeprint'))`);
 assert.equal(await evaluate('[...document.querySelectorAll("#printArea .id-front")].every(card=>card.querySelector(".card-data").getBoundingClientRect().bottom<card.querySelector("footer").getBoundingClientRect().top)'),true);
 await call('Emulation.setEmulatedMedia',{media:''});
 await evaluate(`window.dispatchEvent(new Event('afterprint'))`);
 console.log('PASS: desktop/mobile layout, logo, search, safe preview, save/reload, bulk print size, long text in preview and print.');
 ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
