const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const target=(await(await fetch('http://127.0.0.1:9231/json')).json()).find(t=>t.url.includes('/identity-card'));
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expression=>{for(let n=0;n<60;n++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+expression);};
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1150,deviceScaleFactor:1,mobile:false});
 await call('Page.reload',{ignoreCache:true});
 await wait('document.querySelectorAll(".person").length===2');
 // Give the mock directory distinct pending and added photo groups.
 await evaluate(`fetch('/api/identity-cards/2',{method:'PUT',body:JSON.stringify({status:'Inactive',photo:document.createElement('canvas').toDataURL('image/png')})})`);
 await call('Page.reload',{ignoreCache:true});
 await wait('document.querySelectorAll(".person").length===2');
 assert.equal(await evaluate('document.getElementById("pendingCards").textContent'),'1');
 assert.equal(await evaluate('document.getElementById("photoCards").textContent'),'1');
 await evaluate(`document.getElementById('search').value='no match';document.querySelector('[data-card-filter="pending"]').click()`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),1);
 assert.equal(await evaluate('document.querySelector(".person").dataset.user'),'1');
 await evaluate(`document.querySelector('[data-card-filter="photos"]').click()`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),1);
 assert.equal(await evaluate('document.querySelector(".person").dataset.user'),'2');
 assert.equal(await evaluate('document.querySelector(".person.selected").dataset.user'),'2');
 assert.equal(await evaluate('document.querySelector("#preview .name").textContent'),'Meera Kapoor');
 assert.equal(await evaluate('document.querySelector("[data-card-filter=photos]").getAttribute("aria-pressed")'),'true');
 await evaluate(`window.print=()=>{window.printRequested=true};document.getElementById('printAll').click()`);
 await wait('window.printRequested===true');
 assert.equal(await evaluate('document.querySelectorAll("#printArea .print-pair").length'),1);
 await evaluate(`window.dispatchEvent(new Event('afterprint'));document.querySelector('[data-card-filter="all"]').click()`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),2);
 await evaluate(`fetch('/api/identity-cards/2',{method:'PUT',body:JSON.stringify({status:'Active',photo:null})})`);
 await call('Page.reload',{ignoreCache:true});
 await wait('document.querySelectorAll(".person").length===2');
 await wait('document.querySelectorAll("#preview .id-card").length===2');
 await evaluate(`document.querySelector('[data-card-filter="photos"]').click()`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),0);
 assert.equal(await evaluate('document.querySelectorAll("#preview .id-card").length'),0);
 assert.equal(await evaluate('document.getElementById("printOne").disabled'),true);
 await evaluate(`document.querySelector('[data-card-filter="all"]').click()`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),2);
 assert.equal(await evaluate('document.querySelectorAll("#preview .id-card").length'),2);
 assert.equal(await evaluate('getComputedStyle(document.querySelector("#preview .id-back").parentElement).visibility'),'hidden');
 await evaluate('document.querySelector(".card-turner").click()');
 await wait('!document.querySelector(".card-turner").dataset.turning');
 assert.equal(await evaluate('getComputedStyle(document.querySelector("#preview .id-front").parentElement).visibility'),'hidden');
 assert.equal(await evaluate('getComputedStyle(document.querySelector("#preview .id-back").parentElement).visibility'),'visible');
 assert.equal(await evaluate('(()=>{const back=document.querySelector("#preview .id-back");return back.querySelector(".back-company").getBoundingClientRect().bottom<back.querySelector(".back-id").getBoundingClientRect().top})()'),true);
 await evaluate('document.querySelector(".card-turner").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}))');
 await wait('!document.querySelector(".card-turner").dataset.turning');
 assert.equal(await evaluate('getComputedStyle(document.querySelector("#preview .id-front").parentElement).visibility'),'visible');
 assert.equal(await evaluate('document.querySelector("[name=employee_id]").readOnly'),true);
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 await wait('[...document.querySelectorAll("#preview img")].every(img=>img.complete&&img.naturalWidth>0)');
 let screenshot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('tmp/identity-desktop.png',Buffer.from(screenshot.data,'base64'));
 await evaluate(`document.getElementById('search').value='Meera';document.getElementById('search').dispatchEvent(new Event('input'));`);
 assert.equal(await evaluate('document.querySelectorAll(".person").length'),1);
 await evaluate(`document.querySelector('.person').click();const name=document.querySelector('[name=employee_name]');name.value='Meera & <Kapoor>';name.dispatchEvent(new Event('input',{bubbles:true}));`);
 assert.equal(await evaluate('document.querySelector(".card-data .name").textContent'),'Meera & <Kapoor>');
 assert.equal(await evaluate('document.querySelector(".card-data .name").children.length'),0);
 await evaluate(`const joining=document.querySelector('[name=dob]');joining.value='2024-02-29';joining.dispatchEvent(new Event('input',{bubbles:true}));`);
 assert.equal(await evaluate('document.querySelector("#preview .back-dob").textContent'),'DOB :- 29-02-2024');
 await evaluate(`document.getElementById('editor').requestSubmit()`);
 await wait(`document.getElementById('message').textContent.includes('saved successfully')`);
 await call('Page.reload',{ignoreCache:true});await wait('document.querySelectorAll(".person").length===2');
 await evaluate(`document.querySelector('[data-user="2"]').click()`);
 assert.equal(await evaluate('document.querySelector(".card-data .name").textContent'),'Meera & <Kapoor>');
 assert.equal(await evaluate('document.querySelector("[name=dob]").value'),'2024-02-29');
 await evaluate(`window.print=()=>{window.printRequested=true};document.getElementById('printAll').click()`);
 await wait('window.printRequested===true');
 assert.equal(await evaluate('document.querySelectorAll("#printArea .id-card").length'),4);
 assert.equal(await evaluate('[...document.querySelectorAll("#printArea .back-dob")].some(el=>el.textContent==="DOB :- 29-02-2024")'),true);
 await call('Emulation.setEmulatedMedia',{media:'print'});
 assert.equal(await evaluate('Math.round(document.querySelector("#printArea .id-card").getBoundingClientRect().width)'),204);
 assert.equal(await evaluate('[...document.querySelectorAll("#printArea .id-card")].every(card=>getComputedStyle(card).visibility==="visible")'),true);
 assert.equal(await evaluate('getComputedStyle(document.querySelector("#printArea .print-pair")).breakAfter'),'page');
 assert.equal(await evaluate('(()=>{const pair=document.querySelector("#printArea .print-pair"),sides=pair.querySelectorAll(".id-card");return sides[0].getBoundingClientRect().top===sides[1].getBoundingClientRect().top})()'),true);
 await call('Emulation.setEmulatedMedia',{media:''});
 await evaluate(`window.dispatchEvent(new Event('afterprint'))`);
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 await evaluate('scrollTo(0,400)');
 screenshot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('tmp/identity-mobile.png',Buffer.from(screenshot.data,'base64'));
 // Long allowed values must remain above the card footer.
 await evaluate(`const fields={employee_name:'A very long employee name '.repeat(6).slice(0,150),designation:'Senior regional operations and customer experience manager '.repeat(2).slice(0,100)};for(const [key,value] of Object.entries(fields)){const input=document.querySelector('[name='+key+']');input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));}`);
 assert.equal(await evaluate('document.querySelector(".card-data").getBoundingClientRect().bottom<document.querySelector(".id-front footer").getBoundingClientRect().top'),true);
 assert.equal(await evaluate('(()=>{const name=document.querySelector(".card-data .name");return getComputedStyle(name).whiteSpace==="nowrap"&&name.scrollWidth<=name.clientWidth&&parseFloat(getComputedStyle(name).fontSize)<17})()'),true);
 await evaluate(`document.getElementById('editor').requestSubmit()`);
 await wait(`document.getElementById('message').textContent.includes('saved successfully')`);
 await evaluate(`window.printRequested=false;document.getElementById('printAll').click()`);
 await wait('window.printRequested===true');
 await call('Emulation.setEmulatedMedia',{media:'print'});
 await evaluate(`window.dispatchEvent(new Event('beforeprint'))`);
 assert.equal(await evaluate('[...document.querySelectorAll("#printArea .name, #printArea .designation")].every(name=>getComputedStyle(name).whiteSpace==="nowrap"&&name.scrollWidth<=name.clientWidth)'),true);
 await call('Emulation.setEmulatedMedia',{media:''});
 await evaluate(`window.dispatchEvent(new Event('afterprint'))`);
 await evaluate(`document.querySelector('[name=employee_name]').value='Meera Kapoor';document.querySelector('[name=employee_name]').dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('editor').requestSubmit()`);
 await wait(`document.getElementById('message').textContent.includes('saved successfully')`);
 await evaluate(`window.printRequested=false;document.getElementById('printAll').click()`);
 await wait('window.printRequested===true');
 await call('Emulation.setEmulatedMedia',{media:'print'});
 await evaluate(`window.dispatchEvent(new Event('beforeprint'))`);
 assert.equal(await evaluate('[...document.querySelectorAll("#printArea .id-front")].every(card=>card.querySelector(".card-data").getBoundingClientRect().bottom<card.querySelector("footer").getBoundingClientRect().top)'),true);
 await call('Emulation.setEmulatedMedia',{media:''});
 await evaluate(`window.dispatchEvent(new Event('afterprint'))`);
 console.log('PASS: desktop/mobile layout, logo, search, safe preview, save/reload, bulk print size, long text in preview and print.');
 ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
