const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync('static/incentive.html', 'utf8');
for (const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) new vm.Script(match[1]);
const elements = {nonSalesReport:{hidden:true},nonSalesRates:{innerHTML:''},nonSalesValues:{innerHTML:''},idsFundReport:{hidden:true}, idsFundRows:{innerHTML:''},idsOutletReport:{hidden:true},idsOutletRows:{innerHTML:''}};
const context = {document:{getElementById:id=>elements[id]}, money:{format:n=>n.toFixed(2)}, escapeHtml:s=>s.replaceAll('<','&lt;')};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('  function renderIdsFund('),html.indexOf('  function renderExactIncentive(')),context);
context.renderIdsFund(null);
assert.match(elements.idsFundRows.innerHTML,/Click Calculate/);
context.renderIdsFund({version:1,rows:[]});
assert.match(elements.idsFundRows.innerHTML,/Click Calculate/);
context.renderIdsFund({version:3,rows:[{outlet:'<ALM>',category:'MOB',fund_rate:30,incentive_rate:.125,total_sales:100000,total_incentive:125,ids_fund:37.5}],summary:[{outlet:'<ALM>',total_sales:100000,total_incentive:125,ids_fund:37.5}],totals:{total_sales:100000,total_incentive:125,ids_fund:37.5}});
assert.equal(elements.idsFundReport.hidden,false);
assert.match(elements.idsFundRows.innerHTML,/37.50/);
assert.match(elements.idsFundRows.innerHTML,/&lt;ALM>/);
assert.match(elements.idsFundRows.innerHTML,/GRAND TOTAL/);
assert.match(elements.idsFundRows.innerHTML,/0.125%/);
assert.match(elements.idsFundRows.innerHTML,/Outlet total/);
assert.match(html,/function renderIncentive\(data\)\{renderIdsFund\(data.ids_fund_report\)/);
console.log('IDS Fund rendering, saved-report fallback and JavaScript syntax passed.');

assert.equal(elements.idsOutletReport.hidden,false);
assert.match(elements.idsOutletRows.innerHTML,/37.50/);
assert.match(elements.idsOutletRows.innerHTML,/GRAND TOTAL/);
context.renderNonSales({rows:[{outlet:'ALM',location:'Alambagh',ids_fund:11479,rates:[35,null,12,15,15],values:[4018,null,1377,1722,1722]}],totals:[8180,3739.36,2712,3506,3057]});
assert.match(elements.nonSalesRates.innerHTML,/35%/);
assert.match(elements.nonSalesValues.innerHTML,/4018.00/);
assert.match(elements.nonSalesValues.innerHTML,/3739.36/);
assert.match(elements.nonSalesValues.innerHTML,/Central Service/);
context.renderNonSales(null);
assert.match(elements.nonSalesRates.innerHTML,/Click Calculate/);
assert.match(elements.nonSalesValues.innerHTML,/Click Calculate/);

for(const id of ['salesIncentive','nonSalesIncentive','remainingIncentive'])elements[id]={textContent:''};
vm.runInContext(html.slice(html.indexOf('  function renderIncentiveBalances('),html.indexOf('  function categoryCell(')),context);
const balances={totals:{total_incentive:99999},exact_summary:[{outlet:'ALM',exact_incentive:4018.25},{outlet:'ASH',group:'ALL',total_incentive:100,exact_incentive:50}],grouped_summary:[{total_incentive:30000.12},{total_incentive:40000.23}],ids_fund_report:{version:3,totals:{ids_fund:23371},non_sales_report:{totals:[1,2,3,4,5]}}};
context.renderIncentiveBalances(balances);
assert.equal(elements.salesIncentive.textContent,'4118.25');
assert.equal(elements.nonSalesIncentive.textContent,'23371.00');
assert.equal(elements.remainingIncentive.textContent,'42511.10');
balances.exact_summary[0].exact_incentive=null;
context.renderIncentiveBalances(balances);
assert.equal(elements.salesIncentive.textContent,'Pending');
assert.equal(elements.remainingIncentive.textContent,'Pending');
balances.exact_summary=[{exact_incentive:0}];
balances.grouped_summary=[{total_incentive:0}];
context.renderIncentiveBalances(balances);
assert.equal(elements.salesIncentive.textContent,'0.00');
assert.equal(elements.remainingIncentive.textContent,'-23371.00');
balances.ids_fund_report.version=1;
context.renderIncentiveBalances(balances);
assert.equal(elements.nonSalesIncentive.textContent,'Pending');
assert.equal(elements.remainingIncentive.textContent,'Pending');
context.renderIncentiveBalances({});
assert.equal(elements.salesIncentive.textContent,'Pending');
assert.match(html,/renderIdsFund\(data.ids_fund_report\);renderIncentiveBalances\(data\);/);
console.log('Incentive cards: exact totals, IDS Fund source, group-wise remainder, pending and zero values passed.');
for(const id of ['outletSummaryReport','categoryReport','groupedReport','exactReport','remainingReport','idsFundReport','idsOutletReport','nonSalesReport','salesCard','nonSalesCard','incentiveSelection','showAllReports','nonSalesRateHeading','nonSalesRateTable']){
  elements[id]={hidden:false,setAttribute(name,value){this[name]=value},getAttribute(name){return this[name]},scrollIntoView(){}};
}
vm.runInContext(html.slice(html.indexOf('  function hideIncentiveReports('),html.indexOf('  async function downloadSelectedIncentives(')),context);
context.hideIncentiveReports();
assert.equal(elements.exactReport.hidden,true);
assert.equal(elements.nonSalesReport.hidden,true);
context.toggleIncentiveReport('sales');
assert.equal(elements.exactReport.hidden,false);
assert.equal(elements.salesCard['aria-expanded'],'true');
context.toggleIncentiveReport('non-sales');
assert.equal(elements.exactReport.hidden,true);
assert.equal(elements.nonSalesReport.hidden,false);
assert.equal(elements.incentiveSelection.value,'non-sales');
context.toggleIncentiveReport('non-sales');
assert.equal(elements.nonSalesReport.hidden,true);
assert.match(html,/disabled=false;hideIncentiveReports\(\);document.getElementById\('incentiveDownloads'\).hidden=false/);
console.log('Summary-only default and report card toggles passed.');

context.toggleAllIncentiveReports();
for(const id of ['outletSummaryReport','categoryReport','groupedReport','exactReport','remainingReport','idsFundReport','idsOutletReport','nonSalesReport','nonSalesRateHeading','nonSalesRateTable'])assert.equal(elements[id].hidden,false);
assert.equal(elements.showAllReports.textContent,'Hide');
context.toggleAllIncentiveReports();
assert.equal(elements.outletSummaryReport.hidden,true);
assert.equal(elements.showAllReports.textContent,'Show');
context.toggleAllIncentiveReports();
context.toggleIncentiveReport('sales');
assert.equal(elements.nonSalesRateTable.hidden,true);
console.log('Show All Reports restores every report and toggles back to hidden.');
