// Run against `python -m tests.preview_server` and an isolated Chrome CDP session on 9232.
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const target=(await(await fetch('http://127.0.0.1:9232/json')).json()).find(t=>t.url.includes(':8011'));
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expression=>{for(let n=0;n<100;n++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+expression);};
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const form=async(selector,values)=>evaluate(`(()=>{const f=document.querySelector(${JSON.stringify(selector)});for(const [key,value] of Object.entries(${JSON.stringify(values)}))f.elements[key].value=value;f.requestSubmit(f.querySelector('button[type=submit],button.primary'));})()`);
 const nav=async key=>{await click(`[data-view="${key}"]`);await wait(`document.getElementById('content').querySelector('.panel')!==null`);};
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
 await wait('document.getElementById("auth").hidden===false');
 await form('#authForm',{email:'admin@example.test',password:'PreviewOnly123'});
 await wait('document.querySelector(".welcome")!==null');
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 fs.mkdirSync('test-output',{recursive:true});
 let shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('test-output/overview.png',Buffer.from(shot.data,'base64'));
 await nav('employees');await click('[data-action="employee"][data-id="3"]');
 await form('#dialogForm',{status:'active',role:'employee',department:'Operations',designation:'Executive',outlet:'Head Office',joining_date:'2026-09-01'});
 await wait('document.getElementById("message").textContent==="Employee updated"');
 await nav('rewards');await click('[data-action="new-earning"]');
 await form('#dialogForm',{user_id:'2',month:'2026-09',kind:'incentive',amount:'1250.50',note:'September sales award'});
 await wait('document.getElementById("message").textContent.includes("Earning approved")');
 await nav('payroll');await click('[data-action="new-payroll"]');
 await form('#dialogForm',{user_id:'2',month:'2026-09',basic:'20000',allowances:'1000',deductions:'200'});
 await wait('document.getElementById("message").textContent.includes("Payslip published")');
 assert.equal(await evaluate('document.getElementById("content").textContent.includes("22,050.50")'),true);
 await evaluate('window.print=()=>{window.didPrint=true}');await click('[data-action="payslip"]');
 await wait('window.didPrint===true');
 assert.equal(await evaluate('document.querySelector("#printArea .payslip")!==null'),true);
 await evaluate('window.dispatchEvent(new Event("afterprint"))');
 await nav('identity');await evaluate('window.didPrint=false');await click('[data-action="print-id"]');await wait('window.didPrint===true');
 assert.equal(await evaluate('document.querySelectorAll("#printArea .id-card").length'),2);
 await call('Emulation.setEmulatedMedia',{media:'print'});
 assert.equal(await evaluate('Math.round(document.querySelector("#printArea .id-card").getBoundingClientRect().width)'),204);
 await call('Emulation.setEmulatedMedia',{media:''});await evaluate('window.dispatchEvent(new Event("afterprint"))');
 await click('#logout');await wait('document.getElementById("auth").hidden===false');
 await form('#authForm',{email:'employee@example.test',password:'PreviewOnly123'});await wait('document.querySelector(".welcome")!==null');
 assert.equal(await evaluate('document.querySelector("[data-view=employees]")'),null);
 await click('[data-action="check-in"]');await wait('document.getElementById("message").textContent==="Attendance recorded"');
 await nav('leave');await click('[data-action="new-leave"]');
 await form('#dialogForm',{start_date:'2026-10-10',end_date:'2026-10-11',kind:'Casual',reason:'Family event'});
 await wait('document.getElementById("message").textContent.includes("sent to HR")');
 await nav('payroll');assert.equal(await evaluate('document.querySelectorAll("tbody tr").length'),1);
 await nav('profile');await form('#profileForm',{name:'Aarav Sharma',phone:'9876543210'});
 await wait('document.getElementById("message").textContent==="Profile saved"');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await nav('overview');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync('test-output/mobile.png',Buffer.from(shot.data,'base64'));
 console.log('PASS: HR approval, rewards, payroll, payslip/ID printing, employee isolation, attendance, leave, profile and mobile layout.');
 ws.close();
})().catch(error=>{console.error(error);process.exit(1)});
